// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkQ8a7_TeARbAq35qWC2kJLp3s-GJ8AxQ',
    appId: '1:107010375137:web:fb5358725f0aea59e126a0',
    messagingSenderId: '107010375137',
    projectId: 'internshipecommerce-73944',
    authDomain: 'internshipecommerce-73944.firebaseapp.com',
    storageBucket: 'internshipecommerce-73944.appspot.com',
    measurementId: 'G-3JK097BJWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQMMz5VcOyZ0m9jF2_V6iGri0JYXCxHFQ',
    appId: '1:107010375137:android:76bd38e0e260cd06e126a0',
    messagingSenderId: '107010375137',
    projectId: 'internshipecommerce-73944',
    storageBucket: 'internshipecommerce-73944.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiW7ps_YedZCno1pRj-nZdp6_hfKmfoVs',
    appId: '1:107010375137:ios:d4d3dcd0e69bd74de126a0',
    messagingSenderId: '107010375137',
    projectId: 'internshipecommerce-73944',
    storageBucket: 'internshipecommerce-73944.appspot.com',
    iosClientId: '107010375137-vcq89se7b1873sp89v1s0uls140ka30t.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiW7ps_YedZCno1pRj-nZdp6_hfKmfoVs',
    appId: '1:107010375137:ios:0fae372c45bf44c0e126a0',
    messagingSenderId: '107010375137',
    projectId: 'internshipecommerce-73944',
    storageBucket: 'internshipecommerce-73944.appspot.com',
    iosClientId: '107010375137-64tiffdn7egtiqd688tfs6n3selcd4fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
